pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
cluster_dns: "{{ service_cidr.split('.')[0] }}.{{ service_cidr.split('.')[1] }}.{{ service_cidr.split('.')[2] }}.10"
api_service_ip: "{{ service_cidr.split('.')[0] }}.{{ service_cidr.split('.')[1] }}.{{ service_cidr.split('.')[2] }}.1"

arch_map:
  x86_64: amd64
  aarch64: arm64

arch: "{{ arch_map[ansible_architecture] }}"

# Placeholder
kube_repo_version: ""
