# Install helm
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  delegate_to: "{{ master_ip }}"

- name: Run Helm install script
  command: /tmp/get_helm.sh
  delegate_to: "{{ master_ip }}"
# TODO: Replace "command" module
- name: Add cilium helm repo
  command: helm repo add cilium {{ cni.files }}
  delegate_to: "{{ master_ip }}"

- name: Update helm repos
  command: helm repo update
  delegate_to: "{{ master_ip }}"

- name: Install cilium
  command: |
    helm upgrade --install cilium cilium/cilium \
    --namespace kube-system \
    --set operator.replicas=1 \
    --kubeconfig={{ kubeconfig_dir }}/{{ kubeconfigs.admin.file }}
  delegate_to: "{{ master_ip }}"
  run_once: true
