- include_vars: "{{ playbook_dir }}/roles/kubeconfig/vars/main.yml"

- include_tasks: weave.yml
  when: cni.name == "weave"

- include_tasks: calico.yml
  when: cni.name == "calico"

- include_tasks: cilium.yml
  when: cni.name == "cilium"

- include_tasks: coredns.yml
