vars:
  cert_dir: /etc/kubernetes/pki
  service_cidr: "10.96.0.0/24"
  api_service_ip: "{{ service_cidr.split('.')[0] }}.{{ service_cidr.split('.')[1] }}.{{ service_cidr.split('.')[2] }}.1"
  control_plane_ip: "{{ ansible_default_ipv4.address }}"

  certs:
    - name: ca
      subj: "/CN=KUBERNETES-CA/O=Kubernetes"
      self_signed: true
    - name: kube-controller-manager
      subj: "/CN=system:kube-controller-manager/O=system:kube-controller-manager"
    - name: kube-scheduler
      subj: "/CN=system:kube-scheduler/O=system:kube-scheduler"
    - name: kube-proxy
      subj: "/CN=system:kube-proxy/O=system:node-proxier"
    - name: service-account
      subj: "/CN=service-accounts/O=Kubernetes"
    - name: admin
      subj: "/CN=admin/O=system:masters"
