- name: Ensure kubeconfig directory exists
  file:
    path: "{{ kubeconfig_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Generate kubeconfigs
  template:
    src: kubeconfig.j2
    dest: "{{ kubeconfig_dir }}/{{ item.value.file }}"
    owner: root
    group: root
    mode: "0600"
  vars:
    kubeconfig: "{{ item.value }}"
  loop: "{{ kubeconfigs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
