- name: Set up Kubernetes Master
  hosts: master
  gather_facts: yes
  become: yes

  roles:
    - common
    - client-tools
    - security
    - kubeconfig
    - bootstrap-controlplane
    - cri
    - prepare-tls-bootstrap-workers
