---
- name: Create certificate directory
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: "0755"

# Generate all standard certs
- name: Generate certificate private keys
  command: "openssl genrsa -out {{ cert_dir }}/{{ item.name }}.key 2048"
  args:
    creates: "{{ cert_dir }}/{{ item.name }}.key"
  loop: "{{ certs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Generate certificate CSRs
  command: >
    openssl req -new -key {{ cert_dir }}/{{ item.name }}.key
    -subj "{{ item.subj }}"
    -out {{ cert_dir }}/{{ item.name }}.csr
  args:
    creates: "{{ cert_dir }}/{{ item.name }}.csr"
  loop: "{{ certs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Generate certificates
  command: >
    {% if item.self_signed | default(false) %}
    openssl x509 -req -in {{ cert_dir }}/{{ item.name }}.csr
    -signkey {{ cert_dir }}/{{ item.name }}.key
    -CAcreateserial -out {{ cert_dir }}/{{ item.name }}.crt -days 1000
    {% else %}
    openssl x509 -req -in {{ cert_dir }}/{{ item.name }}.csr
    -CA {{ cert_dir }}/ca.crt -CAkey {{ cert_dir }}/ca.key -CAcreateserial
    -out {{ cert_dir }}/{{ item.name }}.crt -days 1000
    {% endif %}
  args:
    creates: "{{ cert_dir }}/{{ item.name }}.crt"
  loop: "{{ certs }}"
  loop_control:
    label: "{{ item.name }}"

# kube-apiserver cert
- name: Create openssl config for kube-apiserver
  copy:
    dest: "{{ cert_dir }}/openssl-apiserver.cnf"
    content: |
      [req]
      req_extensions = v3_req
      distinguished_name = req_distinguished_name
      [req_distinguished_name]
      [v3_req]
      basicConstraints = critical, CA:FALSE
      keyUsage = critical, nonRepudiation, digitalSignature, keyEncipherment
      extendedKeyUsage = serverAuth
      subjectAltName = @alt_names
      [alt_names]
      DNS.1 = kubernetes
      DNS.2 = kubernetes.default
      DNS.3 = kubernetes.default.svc
      DNS.4 = kubernetes.default.svc.cluster
      DNS.5 = kubernetes.default.svc.cluster.local
      IP.1 = {{ api_service_ip }}
      IP.2 = {{ control_plane_ip }}
      IP.3 = 127.0.0.1

- name: Generate kube-apiserver key
  command: openssl genrsa -out {{ cert_dir }}/kube-apiserver.key 2048
  args:
    creates: "{{ cert_dir }}/kube-apiserver.key"

- name: Generate kube-apiserver CSR
  command: >
    openssl req -new -key {{ cert_dir }}/kube-apiserver.key
    -subj "/CN=kube-apiserver/O=Kubernetes"
    -out {{ cert_dir }}/kube-apiserver.csr -config {{ cert_dir }}/openssl-apiserver.cnf
  args:
    creates: "{{ cert_dir }}/kube-apiserver.csr"

- name: Generate kube-apiserver certificate
  command: >
    openssl x509 -req -in {{ cert_dir }}/kube-apiserver.csr
    -CA {{ cert_dir }}/ca.crt -CAkey {{ cert_dir }}/ca.key -CAcreateserial
    -out {{ cert_dir }}/kube-apiserver.crt -extensions v3_req -extfile {{ cert_dir }}/openssl-apiserver.cnf -days 1000
  args:
    creates: "{{ cert_dir }}/kube-apiserver.crt"
