# CA certificate
- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    size: 2048
    type: RSA

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/{{ certs.ca.name }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    common_name: "KUBERNETES-CA"
    organization_name: "Kubernetes"
    basic_constraints:
      - "CA:TRUE" # marks it as a CA cert
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: yes

- name: Generate CA self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/{{ certs.ca.name }}.crt"
    csr_path: "{{ cert_dir }}/{{ certs.ca.name }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    provider: selfsigned
    selfsigned_create_subject_key_identifier: always_create
    selfsigned_not_after: "{{ certs.ca.expiration }}"
    unsafe_writes: yes

# Other certs
- name: Generate private keys for all other certs
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/{{ item.value.name }}.key"
    size: 2048
    type: RSA
  loop: "{{ (certs | dict2items)[3:] }}"
  loop_control:
    label: "{{ item.key }}"

- name: Generate CSRs for all other certs
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/{{ item.value.name }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ item.value.name }}.key"
    common_name: "{{ item.value.subj.split('/CN=')[1].split('/')[0] }}"
    organization_name: "{{ item.value.subj.split('/O=')[1] }}"
    extended_key_usage: "{{ item.value.extended_key_usage | default(omit) }}"
    extended_key_usage_critical: "{{ item.value.extended_key_usage_critical | default(omit) }}"
  loop: "{{ (certs | dict2items)[3:] }}"
  loop_control:
    label: "{{ item.key }}"

- name: Sign all certificates with CA
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/{{ item.value.name }}.crt"
    csr_path: "{{ cert_dir }}/{{ item.value.name }}.csr"
    ownca_path: "{{ cert_dir }}/{{ certs.ca.name }}.crt"
    ownca_privatekey_path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    ownca_not_after: "{{ item.value.expiration }}"
    provider: ownca
  loop: "{{ (certs | dict2items)[3:] }}"
  loop_control:
    label: "{{ item.key }}"

# Kube-apiserver certificate
- name: Generate kube-apiserver private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/{{ certs.kube_apiserver.name }}.key"
    size: 2048
    type: RSA

- name: Generate kube-apiserver CSR
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/{{ certs.kube_apiserver.name }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ certs.kube_apiserver.name }}.key"
    common_name: "kube-apiserver"
    organization_name: "Kubernetes"
    basic_constraints:
      - "CA:FALSE"
    basic_constraints_critical: yes
    key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
    key_usage_critical: yes
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: yes
    subject_alt_name:
      - "DNS:kubernetes"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster"
      - "DNS:kubernetes.default.svc.cluster.local"
      - "IP:{{ api_service_ip }}"
      - "IP:{{ public_ip }}"
      - "IP:{{ private_ip }}"
      - "IP:127.0.0.1"

- name: Sign kube-apiserver certificate with CA
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/{{ certs.kube_apiserver.name }}.crt"
    csr_path: "{{ cert_dir }}/{{ certs.kube_apiserver.name }}.csr"
    ownca_path: "{{ cert_dir }}/{{ certs.ca.name }}.crt"
    ownca_privatekey_path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    ownca_not_after: "{{ certs.kube_apiserver.expiration }}"
    provider: ownca

# etcd certificate
- name: Generate etcd-server private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_dir }}/{{ certs.etcd.name }}.key"
    size: 2048
    type: RSA

- name: Generate etcd-server CSR
  community.crypto.openssl_csr:
    path: "{{ cert_dir }}/{{ certs.etcd.name }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ certs.etcd.name }}.key"
    common_name: "{{ certs.etcd.name }}"
    organization_name: "{{ certs.etcd.subj}}"
    basic_constraints:
      - "CA:FALSE"
    key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
    subject_alt_name:
      - "IP:{{ private_ip }}"
      - "IP:127.0.0.1"

- name: Sign etcd-server certificate with CA
  community.crypto.x509_certificate:
    path: "{{ cert_dir }}/{{ certs.etcd.name }}.crt"
    csr_path: "{{ cert_dir }}/{{ certs.etcd.name }}.csr"
    ownca_path: "{{ cert_dir }}/{{ certs.ca.name }}.crt"
    ownca_privatekey_path: "{{ cert_dir }}/{{ certs.ca.name }}.key"
    ownca_not_after: "{{ certs.etcd.expiration }}"
    provider: ownca

# Set the encryption key for secrets encryption
- name: Check if encryption key exists
  stat:
    path: "{{ encryption_key_file }}"
  register: key_file

- name: Generate and save encryption key (only once)
  copy:
    content: "{{ lookup('community.general.random_string', length=32) | b64encode }}"
    dest: "{{ encryption_key_file }}"
    mode: "0600"
  when: not key_file.stat.exists

- name: Load encryption key
  slurp:
    src: "{{ encryption_key_file }}"
  register: saved_key

- name: Set encryption key fact
  set_fact:
    encryption_key: "{{ saved_key.content | b64decode }}"

- name: Create encryption config
  template:
    src: encryption-config.yaml.j2
    dest: "{{ encryption_config_file }}"
    mode: "0600"
