cluster:
  name: test
kubeconfig_dir: /var/lib/kubernetes
loadbalancer: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"

kubeconfigs:
  kube_proxy:
    name: kube-proxy
    user: system:kube-proxy
    file: kube-proxy.kubeconfig
    cert: kube-proxy.crt
    key: kube-proxy.key
    server: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"
    isUser: false

  kube_scheduler:
    name: kube-scheduler
    user: system:kube-scheduler
    file: kube-scheduler.kubeconfig
    cert: kube-scheduler.crt
    key: kube-scheduler.key
    server: "127.0.0.1"
    isUser: false

  kube_controller_manager:
    name: kube-controller-manager
    user: system:kube-controller-manager
    file: kube-controller-manager.kubeconfig
    cert: kube-controller-manager.crt
    key: kube-controller-manager.key
    server: "127.0.0.1"
    isUser: false

  admin:
    name: admin
    user: admin
    file: admin.kubeconfig
    cert: admin.crt
    key: admin.key
    server: "127.0.0.1"
    isUser: true

workers_kubeconfigs:
  - name: "{{ worker_hostname }}"
    user: "system:node:{{ worker_hostname }}"
    file: "{{ worker_hostname }}.kubeconfig"
    cert: "{{ worker_hostname }}.crt"
    key: "{{ worker_hostname }}.key"
    server: "{{ master_ip }}"
    isUser: false
