- include_vars: "{{ playbook_dir }}/roles/bootstrap-controlplane/vars/main.yml"

- name: Ensure required directories exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop:
    - { path: "/root/tmp", mode: "1777" }
    - { path: "{{ cert_dir }}", mode: "0755" }
    - { path: "{{ kubeconfig_dir }}", mode: "0755" }
    - { path: "{{ kube_pki_dir }}", mode: "0755" }

- name: Install required packages
  apt:
    name:
      - "openssl"
      - "curl"
      - "apt-transport-https"
      - "ca-certificates"
    state: present
    update_cache: yes
