- name: Load certificate vars
  include_vars: "{{ playbook_dir }}/roles/security/vars/main.yml"

- name: Generate kubeconfigs
  template:
    src: kubeconfig.j2
    dest: "{{ kubeconfig_dir }}/{{ item.value.file }}"
    owner: root
    group: root
    mode: "0600"
  vars:
    kubeconfig: "{{ item.value }}"
  loop: "{{ kubeconfigs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create worker kubeconfigs
  import_tasks: "{{ role_path }}/tasks/worker.yml"
  when: "'kubelet' in components"
